export const types = {
  GET_USERS_TRANSACTIONS: 'GET_USERS_TRANSACTIONS',
  IS_LOADING: 'IS_LOADING',
  GET_ERRORS: 'GET_ERRORS',
  CLEARS_ERRORS: 'CLEARS_ERRORS',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};
